// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCfKLsLk-OyByQvBo_Wa6uY78gNisDRiY',
    appId: '1:810345803409:web:94a3a7e5b261fbafb75930',
    messagingSenderId: '810345803409',
    projectId: 'unimate-310a2',
    authDomain: 'unimate-310a2.firebaseapp.com',
    storageBucket: 'unimate-310a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zhHZiTFMzxl0geVD-V9PaLZpkoWlsC4',
    appId: '1:810345803409:android:983cb830b193c8b3b75930',
    messagingSenderId: '810345803409',
    projectId: 'unimate-310a2',
    storageBucket: 'unimate-310a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfi6IUxcP5OXXRNeuP_CpwPCECa9G8IFM',
    appId: '1:810345803409:ios:c40b3db7d665e05ab75930',
    messagingSenderId: '810345803409',
    projectId: 'unimate-310a2',
    storageBucket: 'unimate-310a2.appspot.com',
    iosBundleId: 'com.example.unimate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfi6IUxcP5OXXRNeuP_CpwPCECa9G8IFM',
    appId: '1:810345803409:ios:f32b8b9a5734ba38b75930',
    messagingSenderId: '810345803409',
    projectId: 'unimate-310a2',
    storageBucket: 'unimate-310a2.appspot.com',
    iosBundleId: 'com.example.unimate.RunnerTests',
  );
}
